timesheetptoProj/accounts/urls.py
from django.urls import path
from .views import register, dashboard, index
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'

urlpatterns = [
    #need to set login & logout redirect url in project settings: LOGIN_REDIRECT_URL = 'accounts/dashboard (need to user templates/registration/login.html)
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register', register, name='register'),
    path('dashboard/', dashboard, name='dashboard'),
    path('index', index, name='home'),
]

timesheetptoProj/timesheetApp/urls.py
from django.urls import path
from . import views

app_name = 'timesheetApp'

urlpatterns = [
    #timesheet homepage
    path('', views.index, name='timesheet-index'),
    #go to template for data entry- calendar and timesheet
    path('entry/', views.entry, name='set-date'),
    #not a new template, get data to populate date fields
    path('timesheet/', views.get_timesheet, name='timesheet-entry'),
    #redirect after submitting timesheet
    path('pto-summary/', views.pto_summary, name='pto-summary'),
]

timesheetptoProj/timesheetptoProj/urls.py
from django.contrib import admin
from django.urls import path, include
#from timesheetApp import urls
#from web_layoutApp import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('timesheet/', include('timesheetApp.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('web_layoutApp.urls')),
]

timesheetptoProj/web_layoutApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index' ),
]

timesheetptoProj/accounts/models.py
from django.db import models

# Create your models here.

timesheetptoProj/pagesApp/models.py
from django.db import models

# Create your models here.
#is not created here
#no migrations to this app

timesheetptoProj/timesheetApp/models.py
from django.db import models
from datetime import datetime
#from django.contrib.auth.models import User
from django.conf import settings

class Timesheet(models.Model):
    #employee = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    employee = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    #employee_id = models.CharField(max_length=200)
    hire_date = models.DateField(null=True) 
    timesheet_stamp = models.DateTimeField(default=datetime.now) 
    timesheet_date = models.DateField(null=True) 
    day_worked_hours = models.DecimalField(max_digits=4, decimal_places=2, null=True)
    

timesheetptoProj/web_layoutApp/models.py
from django.db import models

# Create your models here.

timesheetptoProj/timesheetApp/forms.py
from django import forms

# class DateForm(forms.Form):
#     date = forms.DateField(input_formats=['%d/%m/%Y %H:%M'])

timesheetptoProj/accounts/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
#from django.contrib import messages
#Form below automatically linked to Auth User model. Login and Logout are already created by Class Based Views- see urls.py
from django.contrib.auth.forms import UserCreationForm
#from django.contrib.auth.decorators import login_required

#messages.error(req, 'TESTING MESSAGE')

# def login(req, context={}):
#     # if context != {}:
#     #     #display message in login box
#     #     return render(req, 'login.html', context)
#     if req.method == 'POST':
#         print('LOGIN POST')
#     else:
#         pass
#     return render(req, 'registration/login.html')

# def logout(req):
#     return render(req, 'registration/index.html')

def index(req):
    return render(req, 'home.html')

def dashboard(req):
    return render(req, 'dashboard.html')
    

def register(req):
    if req.method == 'POST':
        form = UserCreationForm(req.POST)
        if form.is_valid():
            form.save()
            return redirect('login/')
            #response = login(req, {'text': 'You are registered. Please sign in.'})
            #return render(req, 'login', {'text': 'You are registered. Please sign in.'})
    else:
        #get form ready to create new user
        form = UserCreationForm()
    #display the registration form in register.html
    return render(req, 'registration/register.html', {'form': form})

timesheetptoProj/pagesApp/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(req):
    return render(req, 'index.html')
    #return HttpResponse('Hello WOrld')

timesheetptoProj/timesheetApp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .calcs import get_week
from .models import Timesheet

#timesheet app homepage
def index(req):
    return render(req, 'index_timesheet.html')

#Calendar widget and timesheet table, modal
@login_required
def entry(req):
    return render(req, 'set_date.html')

#Get date from date picker, and generate daily timesheet dates
@login_required
def get_timesheet(req):
    input = str(req.GET["date"])
    if input != '':
        #get current week's timesheet header dates and days
        wkdy_list, md_list = get_week(input)
    else:
        return render(req, 'set_date.html')
    #got to timesheet entry template
    return render(req, 'set_date.html', 
        {'weekday_list': wkdy_list, 'month_day_list': md_list})

#after timesheet submission, goes to this page
@login_required
#def pto_summary(req, md_list, wk_hrs_list, pto_hrs_list, tot_wk_hrs, tot_pto_hrs):
def pto_summary(req):
    user = req.user
    userObj = User.objects.get(id=user.id)
    md_list = req.POST.getlist("wk_hrs_list")
    print('=====================')
    print(md_list)
    #post timesheet to model 
    # if req.method == 'POST':
    #     for item in wk_hrs_list:
    #         pending_timesheet = Timesheet( employee=userObj, day_worked_hours=item )
    #         pending_timesheet.save()
    #render PTO results
    return render(req, 'pto_summary.html')



# #display timesheet for review and update OR submit [to admin] for approval
# @login_required
# def timesheet_review(req):
#     #headers
#     md_list = req.POST.getlist("month_day_list")
#     wkdy_list = req.POST.getlist("weekday_list")
#     #hours
#     wk_hrs_list = req.POST.getlist("hrs_worked")
#     pto_hrs_list = req.POST.getlist("hrs_pto")
#     wk_hrs_list = [float(hr) for hr in wk_hrs_list]
#     pto_hrs_list = [float(hr) for hr in pto_hrs_list]
#     tot_wk_hrs = sum(wk_hrs_list)
#     tot_pto_hrs = sum(pto_hrs_list)

#     return render(req, 'confirm_entry.html', 
#         {'wk_hrs': wk_hrs_list, 'pto_hrs': pto_hrs_list, 
#             'tot_wk_hrs': tot_wk_hrs, 'tot_pto_hrs': tot_pto_hrs,
#             'weekday_list': wkdy_list, 'month_day_list': md_list})
    

# timesheet_date = models.DateField() 
#     day_worked_hours = models.DecimalField(max_digits=4, decimal_places=2)

# @login_required
# def timesheet_review(req):
#     user = req.user
#     print(user.id)
#     #headers
#     md_list = req.POST.getlist("month_day_list")
#     wkdy_list = req.POST.getlist("weekday_list")
#     #hours
#     wk_hrs = req.POST.getlist("hrs_worked")
#     pto_hrs = req.POST.getlist("hrs_pto")
#     wk_hrs = [float(hr) for hr in wk_hrs]
#     pto_hrs = [float(hr) for hr in pto_hrs]
#     tot_wk_hrs = sum(wk_hrs)
#     tot_pto_hrs = sum(pto_hrs)

#     return render(req, 'confirm_entry.html', 
#         {'wk_hrs': wk_hrs, 'pto_hrs': pto_hrs, 
#             'tot_wk_hrs': tot_wk_hrs, 'tot_pto_hrs': tot_pto_hrs,
#             'weekday_list': wkdy_list, 'month_day_list': md_list})

timesheetptoProj/web_layoutApp/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(req):
    return render(req, 'index.html')
    #return HttpResponse('Hello WOrld')

timesheetptoProj/accounts/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}| Dashboard {% endblock %}

{% block content %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">hello {{ user.get_username }}</h1>
          <p class="lead">Applications created by Dee Nguyen are below.</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'accounts:home' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Dashboard</li>
        </ol>
      </nav>
    </div>
  </section>

  <section id="dashboard" class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>Welcome John</h2>
          <p>Here are the property listings that you have inquired about</p>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Property</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>22</td>
                <td>45 Drivewood Circle</td>
                <td>
                  <a class="btn btn-light" href="#">View Listing</a>
                </td>
              </tr>
              <tr>
                <td>43</td>
                <td>22 Westbrook rd</td>
                <td>
                  <a class="btn btn-light" href="#">View Listing</a>
                </td>
              </tr>
              <tr>
                <td>31</td>
                <td>12 Samson Ave</td>
                <td>
                  <a class="btn btn-light" href="#">View Listing</a>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

timesheetptoProj/accounts/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>ACCOUNTS===============INDEX</h1>
{% endblock %}

timesheetptoProj/timesheetApp/templates/confirm_entry.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Static Example</title>
  <style>body {font-family: Arial, sans-serif;}</style>

  <link rel="stylesheet" type="text/css" href="{% static 'timesheetApp/static/style.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

</head>
<body>

<form action="{% url 'timesheetApp:timesheet-entry' %}" autocomplete="off">
  <input id="datepicker" name="date">
  <input type="submit">
</form>


<div class="">
  <div class="">
    <table style="float: left; padding-top: 100.0px;">
        <tr>
            <th>Hourse Worked</th>
        </tr>
        <tr>
            <th>PTO Used</th>
        </tr>
    </table>
  </div>
  <div class="">
    <form action="{% url 'timesheetApp:pto-summary' %}" method="POST" id="review-form">
        {% csrf_token %}
        <table>
            <tr>
              {% for wd in weekday_list %}
              <th>{{ wd }}</th>
              {% endfor %}
            </tr>          
            <tr>
              {% for md in month_day_list %}
              <th>{{ md }}</th>
              {% endfor %}
            </tr>
            <tr>
              {% for hrs in wk_hrs %}
              <td><input value="{{hrs}}" readonly name="wk_hrs_list"></td>
              {% endfor %}
            </tr>
            <tr>
                {% for hrs in pto_hrs %}
                <td><input value="{{hrs}}" readonly></td>
                {% endfor %}
            </tr>
        </table>

      <div>
        <h1>Total Hours Worked: {{tot_wk_hrs}}</h1>
      </div>
      <br>
      <div>
        <h1>Total Hours PTO: {{tot_pto_hrs}}</h1>
      </div>

      <div>
        <h5>Edit Timesheet</h5>
        <input type="button" id="editButton" value="Edit"></input>       
      </div>  
        
      <div>
        <h5>Submit Timesheet</h5>
        <input type="submit">        
      </div>  
    </form>

  </div>
</div>





  <script>
    $(function () {
      $("#datepicker").datepicker();
      $("#editButton").on('click', function(evt) {
        evt.preventDefault(); 
        $('input:text[readonly]').each(function () { $(this).removeAttr('readonly'); }); 
      });
    });
  </script>

</body>
</html>

timesheetptoProj/timesheetApp/templates/pto_summary.html
{% extends 'base.html' %}

{% block content %}
    <h2>PTO SUMMARY:</h2>
{% endblock %}

timesheetptoProj/timesheetApp/templates/set_date.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Static Example</title>
  <style>body {font-family: Arial, sans-serif;}</style>

  <link rel="stylesheet" type="text/css" href="{% static 'timesheetApp/static/style.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <!-- Fengyuan Chen's Datepicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>

</head>
<body>
<!-- Calendar Widget -->
<form action="{% url 'timesheetApp:timesheet-entry' %}" autocomplete="off">
  <input id="datepicker" name="date">
  <input type="submit" value="Enter Date">
</form>

<!-- Timesheet -->
<form autocomplete="off" method="">
  {% csrf_token %}
<table name="">
	<tr name="line_items">
    <th>Date</th>
    {% for wd in weekday_list %}
    <th>{{wd}}</th>
    {% endfor %}
		<th>&nbsp;</th>
		<th></th>
  </tr>
  <tr name="line_items">
		<th>Category</th>
    {% for md in month_day_list %}
    <th>{{md}}</th>
    {% endfor %}
		<th>&nbsp;</th>
		<th>Total Hours</th>
	</tr>
	<tr name="line_items">
    <td>Work</td>
    {% for md in month_day_list %}
    <td><input type="number" step="0.25" value="0" name="hrs_worked" min="0" max="16" class="enter_wk"></td>
    {% endfor %}    
    <td>&nbsp;</td>
		<td><input type="number" name="" value="" class="tot_wk_hrs" readonly></td>
	</tr>
	<tr name="line_items">
    <td>PTO</td>
    {% for md in month_day_list %}
    <td><input type="number"step="0.25" value="0" name="hrs_pto" min="0" max="8" class="enter_pto"></td>
    {% endfor %}  
		<td>&nbsp;</td>
		<td><input type="number" name="" value="" class="tot_pto_hrs" readonly></td>
	<tr>
		<td colspan="7">&nbsp;</td>
		<td>Subtotal</td>
		<td>&nbsp;</td>
		<td><input type="number" name="subtotal" value="" class="" step="0.25" readonly></td>
	</tr>
	<tr>
		<td colspan="7">&nbsp;</td>
		<td>
			Tax:
			<select name="tax">
				<option value=".06">CT Tax</option>
				<option value=".00">Tax Free</option>
			</select>
		</td>
		<td>&nbsp;</td>
		<td><input type="text" name="tax_total" value="" jAutoCalc="{sub_total} * {tax}"></td>
	</tr>
	<tr>
		<td colspan="7">&nbsp;</td>
		<td>Total</td>
		<td>&nbsp;</td>
		<td><input type="text" name="grand_total" value="" jAutoCalc="{sub_total} + {tax_total}"></td>
	</tr>
</table>
</form>

<!-- Bring up modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter" onclick="display_inputs()">
  Review Timesheet
</button>



<!-- MODAL -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <!-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span> -->
        </button>
      </div>
      
      <div class="modal-body">
      <div>
        <form action="{% url 'timesheetApp:pto-summary' %}" method="POST" id="review-form">
          {% csrf_token %}
        <table name="">
          <tr name="line_items">
            <th>Date</th>
            {% for wd in weekday_list %}
            <th>{{wd}}</th>
            {% endfor %}
            <th>&nbsp;</th>
            <th></th>
          </tr>
          <tr name="line_items">
            <th>Category</th>
            {% for md in month_day_list %}
            <th>{{md}}</th>
            {% endfor %}
            <th>&nbsp;</th>
            <th>Total Hours</th>
          </tr>
          <tr name="line_items">
            <td>Work</td>
            {% for md in month_day_list %}
            <td><input value="" name="wk_hrs_list" class="wk_hrs" readonly></td>
            {% endfor %}    
            <td>&nbsp;</td>
            <td><input type="number" name="" value="" class="tot_wk_hrs" readonly></td>
          </tr>
          <tr name="line_items">
            <td>PTO</td>
            {% for md in month_day_list %}
            <td><input value="" name="pto_hrs_list" class="pto_hrs" readonly></td>
            {% endfor %}  
            <td>&nbsp;</td>
            <td><input type="number" name="" value="" class="tot_pto_hrs" readonly></td>
          <tr>
            <td colspan="7">&nbsp;</td>
            <td>Subtotal</td>
            <td>&nbsp;</td>
            <td><input type="number" name="subtotal" value="" class="" step="0.25" readonly></td>
          </tr>
          <tr>
            <td colspan="7">&nbsp;</td>
            <td>
              Tax:
              <select name="tax">
                <option value=".06">CT Tax</option>
                <option value=".00">Tax Free</option>
              </select>
            </td>
            <td>&nbsp;</td>
            <td><input type="text" name="tax_total" value="" jAutoCalc="{sub_total} * {tax}"></td>
          </tr>
          <tr>
            <td colspan="7">&nbsp;</td>
            <td>Total</td>
            <td>&nbsp;</td>
            <td><input type="text" name="grand_total" value="" jAutoCalc="{sub_total} + {tax_total}"></td>
          </tr>
        </table>

              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Edit</button>
                <input type="submit" class="btn btn-primary">
              </div>
            </form>
          </div>

    </div>
  
  
  </div>
</div>






<script>
  
  var wk_hrs = []
  var pto_hrs = []

  //onclick for modal to display inputs
  function display_inputs(wk_hrs, pto_hrs){
    //serialize a collection of objs
    wk_hrs = $('input[name ="hrs_worked"]').serializeArray();
    pto_hrs = $('input[name ="hrs_pto"]').serializeArray();
    
    //display list of obj.values to a list of input tags
    var i = 0;
    $('input[class ="wk_hrs"]').empty();
    $.each( $('input[class ="wk_hrs"]'), function(idx, item){
        $(this).attr('value', wk_hrs[i++].value)
      });  
    var j = 0;
    $('input[class ="pto_hrs"]').empty();
    $.each( $('input[class ="pto_hrs"]'), function(idx, item){
        $(this).attr('value', pto_hrs[j++].value)
      });  

  }


  function calcTot(selectors) {
    total = 0
    $(selectors).each(function () {
    var input = parseFloat($(this).val());
    total += input
    });
    return total
  };

  var tot_wk_hrs = 0
  var tot_pto_hrs = 0
  //calc total wk hrs at input
  $('input[class ="enter_wk"]').on('click keyup', function () {
    tot_wk_hrs = calcTot('input[class ="enter_wk"]')
    $('.tot_wk_hrs').val(tot_wk_hrs)
    updateSubtot(tot_wk_hrs, tot_pto_hrs)
    });
  //calc total pto hrs at input
  $('input[class ="enter_pto"]').on('click keyup',function () {
    tot_pto_hrs = calcTot('input[class ="enter_pto"]')
    $('.tot_pto_hrs').val(tot_pto_hrs)
    updateSubtot(tot_wk_hrs, tot_pto_hrs)
  });

  //calc total wk + pto hrs at input
  function updateSubtot(tot_wk_hrs, tot_pto_hrs){
    var total = tot_wk_hrs + tot_pto_hrs 
    $('input[name ="subtotal"]').val(total)
  }


  //run at page load: 
  $(function () {
    //calendar date-picker
    $("#datepicker").datepicker();
        
  });
</script>
</body>
</html>

timesheetptoProj/web_layoutApp/templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio {% block title %} {% endblock%}</title>
    <!-- will go to static root to find files -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">  
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">  
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
    <link rel="stylesheet" href="{% static 'css/lightbox.min.css' %}">  
</head>
<body>
    <section id="top-bar" class="p-3">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <i class="fas fa-phone"></i> (617)-555-5555
            </div>
            <div class="col-md-4">
              <i class="fas fa-envelope-open"></i> contact@btrealestate.co
            </div>
            <div class="col-md-4">
              <div class="social text-right">
                <a href="#">
                  <i class="fab fa-twitter"></i>
                </a>
                <a href="#">
                  <i class="fab fa-facebook"></i>
                </a>
                <a href="#">
                  <i class="fab fa-linkedin"></i>
                </a>
                <a href="#">
                  <i class="fab fa-instagram"></i>
                </a>
                <a href="#">
                  <i class="fab fa-pinterest"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>


    <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
        <div class="container">
          <a class="navbar-brand" href="index.html">
            <img src="{% static 'img/logo.png' %}" class="logo" alt="">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
              <li class="nav-item active mr-3">
                <a class="nav-link" href="index.html">Home</a>
              </li>
              <li class="nav-item mr-3">
                <a class="nav-link" href="about.html">About</a>
              </li>
              <li class="nav-item mr-3">
                <a class="nav-link" href="{% url 'timesheetApp:set-date' %}">Timesheet/PTO</a>
              </li>
            </ul>
    
            <ul class="navbar-nav ml-auto">
              <!-- add conditional presentation to list item -->
              {% if user.is_authenticated %}
                    <li
                    {% if 'register' in request.path %}
                        class="nav-item active mr-3"
                    {% else %}
                        class="nav-item mr-3"
                    {% endif %}
                     >
                    <a class="nav-link" href="{% url 'accounts:logout' %}">
                    <i class="fas fa-user-minus"></i> Logout</a>
                    </li>
              {% else %}
                    <li
                        {% if 'register' in request.path %}
                            class="nav-item active mr-3"
                        {% else %}
                            class="nav-item mr-3"
                        {% endif %}
                    >
                    <a class="nav-link" href="{% url 'accounts:register' %}">
                    <i class="fas fa-user-plus"></i> Register</a>
                    </li>
                    <li
                        {% if 'login' in request.path %}
                            class="nav-item active mr-3"
                        {% else %}
                            class="nav-item mr-3"
                        {% endif %}
                    >
                    <a class="nav-link" href="{% url 'accounts:login' %}">
                    <i class="fas fa-sign-in-alt"></i>
                    Login</a>
                    </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    
    <h1>FROM BASE</h1>
    {% block content %}
    {% endblock %}


<footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year"></span> neoObx
</footer>

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/lightbox.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>


</script>

</body>
</html>

timesheetptoProj/web_layoutApp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Home page from web layout</h1>
</body>
</html>